<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var array $data
 */

$this->layout('system::layout/default');
?>
<div class="row">
    <div class="col-md-6">
        <form method="post" class="mb-3" action="<?= $data['storeUrl'] ?>">
            <h4><?= __('Feedback') ?></h4>

            <?= $this->fetch(
                'system::forms/simple_form',
                [
                    'fields' => $data['formFields'],
                    'errors' => $data['validationErrors'],
                ]
            ); ?>

            <button type="submit" name="submit" class="btn btn-primary"><?= __('Submit') ?></button>
        </form>
    </div>
</div>
